Add some initial input validation prior to smoke-test job execution

diff --git a/.github/workflows/run_smoke_test.yml b/.github/workflows/run_smoke_test.yml
--- a/.github/workflows/run_smoke_test.yml
+++ b/.github/workflows/run_smoke_test.yml
@@ -6,8 +6,8 @@ on:
       - "main"
   push:
     # Uncomment when testing locally
-    #paths:
-    #  - ".github/workflows/run_smoke_test.yml"
+    paths:
+      - ".github/workflows/run_smoke_test.yml"
     #  - ".github/actions/setup-dependencies-windows/action.yml"
     #  - ".github/actions/setup-dependencies-macos/action.yml"
     branches:
@@ -29,9 +29,33 @@ on:
         description: "Choose OPA version"
         required: true
         type: string
-        default: "0.59.0"
+        default: "0.60.0"
 
 jobs:
+  validate-workflow-inputs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate Workflow Dispatch Inputs
+        run: |
+          os_input="${{ inputs.os }}"
+          pythonversion_input="${{ inputs.python-version }}"
+
+          # Validate the input format with a regular expression
+          if [[ ! "$os_input" =~ ^\['[^']+'(, '[^']+')*\]$ ]]; then
+            echo "Invalid OS input: $os_input. Expected format: ['os-1', 'os-2', ...]"
+            exit 1
+          else
+            echo "OS input is valid: $os_input"
+          fi
+
+          # Validate the input format with a regular expression
+          if [[ ! "$pythonversion_input" =~ ^\['[^']+'(, '[^']+')*\]$ ]]; then
+            echo "Invalid Python version input: $pythonversion_input. Expected format: ['3.10', '3.11', ...]"
+            exit 1
+          else
+            echo "Python version input is valid: $pythonversion_input"
+          fi
+          
   smoke-test:
     strategy:
       fail-fast: false
@@ -57,16 +81,16 @@ jobs:
         if: ${{ matrix.os == 'windows-latest' }}
         uses: ./.github/actions/setup-dependencies-windows
         with:
-          operating-system: "windows"
-          opa-version: "0.60.0"
+          os: "windows"
+          opa-version: ${{ inputs.opa-version }}
           python-version: ${{ matrix.python-version }}
       
       - name: Setup Dependencies (macOS)
         if: ${{ matrix.os == 'macos-latest' }}
         uses: ./.github/actions/setup-dependencies-macos
         with:
-          operating-system: "macos"
-          opa-version: "0.60.0"
+          os: "macos"
+          opa-version: ${{ inputs.opa-version }}
           python-version: ${{ matrix.python-version }}
       
       - name: Setup credentials for service account
