Policy API Integration (#499)
* move certain top-level directories into "scubagoggles"

* implementation with policy API

* correct anchor to setup utility

* first step in fixing smoke test workflow

* improve setup for smoke test; accommodate AMD64 OPA on ARM64 macOS

* implemented initial feedback from pull request

* argument parser: ensure credentials is a Path

* Complete implementation of service account credentials for policy API

* fix GwsAuth for service accounts - they have no token file
getopa: tolerate missing "v" in specified version

* documentation: moved from with "scubagoggles" subdirectory to top-level directory

* build: create output directory if non-existent

* documentation: minor changes

* setup: download OPA; resolve other PR issues

* smoke_test: remove default value for "subjectemail" in test_scubagoggles_output()

* groups 4.1, 5.1: correct for probable Google changes in enumeration values
drive 1.3, 1.4, 1.5, 1.7: correct misunderstanding of sharing option flags

* drive rego: remove unused import

* commoncontrols 3.1: remove policy API check for employee ID challenge (see 11/6 change)
commoncontrols 4.1: use "friendly" value in non-compliance message

* commoncontrols: remove 9.1, 9.2 policy API implementation

* commoncontrols: check "takeout_service_status" in 12.1

* policy_api: implement policy reduction and apply default values
scuba_argument_parser: fix bug in converting argument value data types
drive rego: fix 6.1 for subOUs/groups
policy_api: add ability to dump Google's raw policy response
installation & OPA instructions: add more detail about setup downloading OPA

diff --git a/.github/workflows/run_release.yml b/.github/workflows/run_release.yml
--- a/.github/workflows/run_release.yml
+++ b/.github/workflows/run_release.yml
@@ -1,4 +1,4 @@
-on: 
+on:
   workflow_dispatch:
     inputs:
       releaseName:
@@ -14,33 +14,42 @@ name: Build Release
 
 jobs:
   build-and-deploy:
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     env:
+      PYTHON_VERSION: "3.12"
       RELEASE_VERSION: ${{ inputs.version }}
     permissions:
       contents: write
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-      with:
-        path: repo
-        ref: main
-    - name: Package Repo for release
-      shell: pwsh
-      run: |
-        $PackageName = "scubagoggles"
-        Remove-Item -Recurse -Force repo -Include .git*
-        Move-Item -Path repo -Destination "${PackageName}-${env:RELEASE_VERSION}" -Force
-        Compress-Archive -Path "${PackageName}-${env:RELEASE_VERSION}" -DestinationPath "${PackageName}-${env:RELEASE_VERSION}.zip"
-        Get-ChildItem -Path . | Write-Output
-    - name: release
-      uses: softprops/action-gh-release@v1
-      id: create_release
-      with:
-        draft: true
-        prerelease: false
-        name: v${{ inputs.releaseName }}
-        tag_name: v${{ inputs.version }}
-        files: scubagoggles-${{ inputs.version }}.zip
-        generate_release_notes: true
-        fail_on_unmatched_files: true
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Set up Python ${{ env.PYTHON_VERSION }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+      - name: Install Python dependencies
+        run: pip install -r requirements.txt
+      - name: Package Repo for release
+        shell: bash
+        run: |
+          reqv="${{ inputs.version }}"
+          reqv="${reqv//[[:space:]]/}"
+          [[ ! "$reqv" =~ ^[0-9]{1,2}(\.[0-9]{1,2}){2}$ ]] \
+            && echo "invalid request version: $reqv" && exit 1
+          sgv=$(grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' scubagoggles/__init__.py)
+          [[ "$reqv" == "$sgv" ]] \
+            || (echo "version mismatch - current: $sgv" && exit 1)
+          ./scubagoggles/utils/build.sh -r "$PWD" -t "$GITHUB_REF_NAME"
+      - name: release
+        uses: softprops/action-gh-release@v1
+        id: create_release
+        with:
+          draft: true
+          prerelease: false
+          name: v${{ inputs.releaseName }}
+          tag_name: v${{ inputs.version }}
+          files: |
+            scubagoggles-*-py3-none-any.whl
+            scubagoggles-*.tar.gz
+          generate_release_notes: true
+          fail_on_unmatched_files: true
